flags: {}
packages:
- ethereum-rlp
- ethereum-util
- ethereum-merkle-patricia-db
- ethereum-encryption
- ethereum-data-sql
- hminer
- ethereum-client-haskell
- ethereum-vm
- p2p-server
- hserver-eth
- solidity-abi
- ethereum-query
- location:
    git: https://github.com/haskoin/haskoin
    commit: b71bcfa4701e129b69776e6951fe0bb7c8b26ea3
extra-deps:
- AES-0.2.9
- Crypto-4.2.5.1
- SHA2-0.2.5
- arithmoi-0.4.1.3
- directory-1.2.3.1
- json-rpc-0.2.1.6
- leveldb-haskell-0.6.3
- murmur3-1.0.0
- nibblestring-0.0.3
- pbkdf-1.1.1.1
- yesod-raml-0.1.4
resolver: lts-3.4
